## Quiz #0101

#### Provide the answers in Python code:

1).  In the class A, students' heights are:

161.5 <br>
165.9 <br>
168.7 <br>
163.1 <br>
170.8 <br>
167.2 <br>

Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
    
    Students_height_A = [161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
    list_sum = 0  
    for number in Students_height_A:
        list_sum = int(number) + list_sum
 
    #calculate the average 
    list_avg = list_sum / len(Students_height_A)
    print('The average of the height of the students  is: ', list_avg)



The average of the height of the students  is:  165.66666666666666


2).  In the class B, students' heights are:

172.5 <br>
162.9 <br>
161.7 <br>
160.1 <br>
161.8 <br>
169.2 <br>

Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
    
    Students_height_B = [172.5, 162.9, 161.7, 160.1, 161.8, 169.2]
    list_sum = 0  
    for number in Students_height_B:
        list_sum = int(number) + list_sum
 
    #calculate the average 
    list_avg = list_sum / len(Students_height_B)
    print('The average of the height of the students  is: ', list_avg)
    



The average of the height of the students  is:  164.16666666666666


3). The class A and the class B are joined together to form the class AB. Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
data1 = [161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
data2 = [172.5, 162.9, 161.7, 160.1, 161.8, 169.2]
data = data1 + data2
def meanoflist(list):
    res=0
    for i in list:
       res = res+i
    mean = res/ len(list)
    return round( mean,2)
meanoflist(data)   

165.45

[link text](https://)4). Sort the heights of the class AB.

In [ ]:
data1=[161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
data2=[172.5, 162.9, 161.7, 160.1, 161.8, 169.2]
numbers = data1+data2 
numbers.sort()
  
print(numbers)

[160.1, 161.5, 161.5, 161.7, 161.8, 162.9, 163.1, 163.1, 165.9, 165.9, 167.2, 167.2, 168.7, 168.7, 169.2, 170.8, 170.8, 172.5]


5). The class C is formed with students with the height less than 165. Make a list 'C' containing the heights of the class C.

In [ ]:
c=[]
data1=[161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
data2=[172.5, 162.9, 161.7, 160.1, 161.8, 169.2]
numbers = data1+data2
for x in numbers:
     if x < 165:
      c.append(x)
print(c)

[161.5, 163.1, 162.9, 161.7, 160.1, 161.8]


6). The class D is formed with students with the height larger than 160 and less than 170. Make a list containing the heights of the class D.

In [ ]:
D=[]
data1=[161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
data2=[172.5, 162.9, 161.7, 160.1, 161.8, 169.2]
numbers = data1+data2
for x in numbers:
     if x >  160 and x < 170 :
      D.append(x)
print(D)

[161.5, 165.9, 168.7, 163.1, 167.2, 162.9, 161.7, 160.1, 161.8, 169.2]
